[package]
name = "spike-cassowary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cassowary = "0.3.0"
color-eyre = "0.6.2"
itertools = "0.12.0"
